In [5]:
import numpy as np
import cv2

In [93]:
# Python code to find the co-ordinates of 
# the contours detected in an image. 
import numpy as np 
import cv2 

# Reading image 
font = cv2.FONT_HERSHEY_COMPLEX 
img2 = cv2.imread('maze07.jpg', cv2.IMREAD_COLOR) 

cn = []
areas = []

# Reading same image in another 
# variable and converting to gray scale. 
img = cv2.imread('maze07.jpg', cv2.IMREAD_GRAYSCALE) 

# Converting image to a binary image 
# ( black and white only image). 
_, threshold = cv2.threshold(img, 110, 255, cv2.THRESH_BINARY) 

kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(threshold,kernel,iterations = 1)
# Detecting contours in image. 
contours, _= cv2.findContours(erosion, cv2.RETR_TREE, 
							cv2.CHAIN_APPROX_SIMPLE) 

area2 = 0
area3 = 0
t = 0

# Going through every contours found in the image. 
for cnt in contours : 
	area = cv2.contourArea(cnt)
	approx = cv2.approxPolyDP(cnt, 0.01*cv2.arcLength(cnt, True), True)
	print(len(approx))
	if area > area2:
		if area > area2 and area < area3:
			area2 = area
			cn = []
			t = 1
		elif area < area2 and area < area3:
			pass
		else:
			area3 = area
# 		area2 = area
# 		area3 = area
		cn = []
		t = 1
	areas.append(area)
	approx = cv2.approxPolyDP(cnt, 0.009 * cv2.arcLength(cnt, True), True) 

	# draws boundary of contours. 
	cv2.drawContours(img2, [approx], 0, (0, 0, 255), 5) 

	# Used to flatted the array containing 
	# the co-ordinates of the vertices. 
	n = approx.ravel() 
	i = 0
    
	if len(approx) == 4 and t == 1:
		for j in n : 
			if(i % 2 == 0): 
				x = n[i] 
				y = n[i + 1] 
# 				if t == 1:
# 					cn.append([x,y])

				cn.append([x,y])            
				string = str(x) + " " + str(y) 

#                 if(i == 0): 
#                     # text on topmost co-ordinate. 
#                     cv2.putText(img2, "Arrow tip", (x, y), 
#                                     font, 0.5, (255, 0, 0)) 
#                 else: 
#                     # text on remaining co-ordinates. 
#                     cv2.putText(img2, string, (x, y), 
#                             font, 0.5, (0, 255, 0)) 
			i = i + 1; t = 0
	t = 0    
# # Showing the final image. 
# cv2.imshow('image2', img2) 

# # Exiting the window if 'q' is pressed on the keyboard. 
# if cv2.waitKey(0) & 0xFF == ord('q'): 
# 	cv2.destroyAllWindows() 


4
4
26


In [94]:
for i in range(len(cn)):
    if cn[i][0] > 100 and cn[i][1] < 100:
        x2 = cn[i][0]
        y2 = cn[i][1]
    if cn[i][0] > 100 and cn[i][1] > 100:
        x4 = cn[i][0]
        y4 = cn[i][1]
    if cn[i][0] < 100 and cn[i][1] > 100:
        x3 = cn[i][0]
        y3 = cn[i][1]
    if cn[i][0] < 100 and cn[i][1] < 100:
        x1 = cn[i][0]
        y1 = cn[i][1]

s = cn.sort()        
print(x4,y4)

451 455


In [95]:
img = cv2.imread("maze07.jpg")
pts1 = np.float32([[x1, y1], [x2, y2], [x3, y3], [x4, y4]])
pts2 = np.float32([[0, 0], [512, 0], [0, 512], [512, 512]])

matrix = cv2.getPerspectiveTransform(pts1, pts2)
result = cv2.warpPerspective(img, matrix, (512, 512))

# cv2.imshow("Image", img)
# cv2.imshow("Perspective transformation", result)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [33]:
print(result)

[[[138 142 147]
  [111 115 120]
  [ 92  96 101]
  ...
  [132 137 138]
  [132 137 138]
  [131 136 137]]

 [[126 130 135]
  [ 82  86  91]
  [ 45  49  54]
  ...
  [103 108 109]
  [100 105 106]
  [ 99 104 105]]

 [[132 136 141]
  [ 80  84  89]
  [ 28  31  36]
  ...
  [ 40  45  46]
  [ 38  43  44]
  [ 41  46  47]]

 ...

 [[ 69  74  77]
  [ 18  23  26]
  [  9  13  17]
  ...
  [  0   3   6]
  [ 13  18  21]
  [ 51  60  63]]

 [[ 75  80  83]
  [ 32  37  40]
  [ 23  27  31]
  ...
  [  6   8  11]
  [ 17  22  25]
  [ 52  61  64]]

 [[ 98 103 106]
  [ 67  72  75]
  [ 60  64  67]
  ...
  [ 30  36  39]
  [ 38  45  48]
  [ 70  80  83]]]


In [11]:
# Python code to find the co-ordinates of 
# the contours detected in an image. 
import numpy as np 
import cv2 

# Reading image 
# font = cv2.FONT_HERSHEY_COMPLEX 


cn = []
areas = []

# Reading same image in another 
# variable and converting to gray scale. 
# img = cv2.imread('maze06.jpg', cv2.IMREAD_GRAYSCALE) 

img = cv2.cvtColor(result, cv2.COLOR_BGR2GRAY)
mask = np.zeros(img.shape,np.uint8)
cv2.drawContours(mask,[cnt],0,255,-1)
pixelpoints = cv2.findNonZero(mask)

# # Converting image to a binary image 
# # ( black and white only image). 
_, threshold = cv2.threshold(img, 110, 255, cv2.THRESH_BINARY) 

# # Detecting contours in image. 
contours, _= cv2.findContours(threshold, cv2.RETR_TREE, 
							cv2.CHAIN_APPROX_NONE) 

# area2 = 0
# area3 = 0
# t = 0

# Going through every contours found in the image. 
for cnt in contours : 
	area = cv2.contourArea(cnt)
	approx = cv2.approxPolyDP(cnt, 0.01*cv2.arcLength(cnt, True), True)
	print(len(approx))
	if area > area2:
		if area > area2 and area < area3:
			area2 = area
			cn = []
			t = 1
		elif area < area2 and area < area3:
			pass
		else:
			area3 = area
# 		area2 = area
# 		area3 = area
		cn = []
		t = 1
	areas.append(area)
	approx = cv2.approxPolyDP(cnt, 0.009 * cv2.arcLength(cnt, True), True) 

	# draws boundary of contours. 
	cv2.drawContours(img2, [approx], 0, (0, 0, 255), 5) 

	# Used to flatted the array containing 
	# the co-ordinates of the vertices. 
	n = approx.ravel() 
	i = 0
    
	if len(approx) == 4 and t == 1:
		for j in n : 
			if(i % 2 == 0): 
				x = n[i] 
				y = n[i + 1] 
# 				if t == 1:
# 					cn.append([x,y])

				cn.append([x,y])            
				string = str(x) + " " + str(y) 

			i = i + 1; t = 0
	t = 0 
# img = cv2.imread('maze06.jpg', cv2.IMREAD_COLOR) 
    
# cv2.drawContours(result, contours, -1, (0, 255, 0), 3) 

# cv2.imshow('Contours', result) 
# cv2.waitKey(0) 
# cv2.destroyAllWindows() 

1
22
6
2
4


In [17]:
print(pixelpoints)

[[[ 0  0]]

 [[ 1  0]]

 [[ 0  1]]

 [[ 0  2]]

 [[ 0  3]]

 [[ 0  4]]

 [[ 0  5]]

 [[ 0  6]]

 [[ 0  7]]

 [[ 0  8]]

 [[ 0  9]]

 [[ 0 10]]

 [[ 0 11]]

 [[ 0 12]]

 [[ 0 13]]

 [[ 0 14]]

 [[ 0 15]]

 [[ 0 16]]

 [[ 0 17]]

 [[ 0 18]]

 [[ 0 19]]

 [[ 0 20]]

 [[ 0 21]]

 [[ 0 22]]

 [[ 0 23]]

 [[ 0 24]]

 [[ 0 25]]

 [[ 0 26]]

 [[ 0 27]]

 [[ 0 28]]

 [[ 0 29]]

 [[ 0 30]]

 [[ 0 31]]

 [[ 0 32]]

 [[ 0 33]]

 [[ 0 34]]

 [[ 0 35]]

 [[ 0 36]]

 [[ 0 37]]

 [[ 0 38]]

 [[ 0 39]]

 [[ 0 40]]

 [[ 0 41]]

 [[ 0 42]]

 [[ 0 43]]

 [[ 0 44]]

 [[ 0 45]]

 [[ 0 46]]

 [[ 0 47]]

 [[ 0 48]]]


In [16]:
for i in range(int(512/10)):
    print(contours[i])
    for j in range(int(512/10)):
        print(i,j)

[[[ 0 53]]]
0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
0 10
0 11
0 12
0 13
0 14
0 15
0 16
0 17
0 18
0 19
0 20
0 21
0 22
0 23
0 24
0 25
0 26
0 27
0 28
0 29
0 30
0 31
0 32
0 33
0 34
0 35
0 36
0 37
0 38
0 39
0 40
0 41
0 42
0 43
0 44
0 45
0 46
0 47
0 48
0 49
0 50
[[[22  5]]

 [[21  6]]

 [[20  6]]

 ...

 [[25  6]]

 [[24  5]]

 [[23  5]]]
1 0
1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
1 10
1 11
1 12
1 13
1 14
1 15
1 16
1 17
1 18
1 19
1 20
1 21
1 22
1 23
1 24
1 25
1 26
1 27
1 28
1 29
1 30
1 31
1 32
1 33
1 34
1 35
1 36
1 37
1 38
1 39
1 40
1 41
1 42
1 43
1 44
1 45
1 46
1 47
1 48
1 49
1 50
[[[460  19]]

 [[461  18]]

 [[462  18]]

 [[463  19]]

 [[462  20]]

 [[461  20]]]
2 0
2 1
2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
2 10
2 11
2 12
2 13
2 14
2 15
2 16
2 17
2 18
2 19
2 20
2 21
2 22
2 23
2 24
2 25
2 26
2 27
2 28
2 29
2 30
2 31
2 32
2 33
2 34
2 35
2 36
2 37
2 38
2 39
2 40
2 41
2 42
2 43
2 44
2 45
2 46
2 47
2 48
2 49
2 50
[[[148   0]]

 [[149   0]]

 [[150   0]]

 ...

 [[151   0]]

 [[150   0]]

 [[149   0]]]
3

IndexError: list index out of range

In [98]:
# cv2.drawContours(result, contours, -1, (0, 255, 0), 3) 
# ret,im = cv2.threshold(result,127,255,cv2.THRESH_BINARY)
# kernel = np.ones((5,5),np.uint8)
# erosion = cv2.erode(im,kernel,iterations = 0)
# r = erosion
# size = 51
i = 9
j = 6
block = r[int(i*size):int((i+1)*size),int(j*size):int((j+1)*size)]
up    = (not bool(np.all(block[0,int(size/2)]))) *2
down  = (not bool(np.all(block[int(size-1),int(size/2)])))*8
left  = (not bool(np.all(block[int(size/2),0]))) *1
right = (not bool(np.all(block[int(size/2),int(size-1)])))*4
print(block[int(size-1),int(size/2)])
print(block[0,int(size/2)])
print(block[int(size/2),0])
print(up,down,left,right)
cv2.imshow('Contours', r) 
cv2.waitKey(0) 
cv2.destroyAllWindows() 
print((im[5][459]))
print(up+down+left+right)

[0 0 0]
[0 0 0]
[255 255 255]
2 8 0 0
[0 0 0]
10


In [97]:
ret,im = cv2.threshold(result,127,255,cv2.THRESH_BINARY)
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(im,kernel,iterations = 2)
dilation = cv2.dilate(erosion,kernel,iterations = 1)
r = dilation
size = 51.2

mat = []

for i in range(10):
    mat.append([])
    for j in range(10):
        up = right = down = left = 0
        block = r[int(i*size):int((i+1)*size),int(j*size):int((j+1)*size)]
        up    = (not bool(np.any(block[0,int(size/2)]))) *2
        down  = (not bool(np.any(block[int(size-1),int(size/2)])))*8
        left  = (not bool(np.any(block[int(size/2),0]))) *1
        right = (not bool(np.any(block[int(size/2),int(size-1)])))*4
        total = up + down + left + right
#         cv2.imshow('Contours', block) 
#         cv2.waitKey(0) 
#         cv2.destroyAllWindows() 
#         print(total)
        mat[i].append(total)

print(mat)
        

[[3, 14, 3, 10, 10, 10, 10, 2, 10, 6], [5, 3, 12, 11, 6, 3, 6, 13, 3, 4], [5, 9, 2, 10, 12, 5, 9, 6, 5, 13], [1, 14, 5, 3, 6, 9, 6, 5, 9, 6], [9, 10, 12, 5, 9, 10, 12, 5, 3, 12], [3, 10, 6, 5, 7, 3, 10, 12, 9, 6], [5, 11, 8, 12, 5, 5, 3, 6, 3, 12], [5, 7, 3, 10, 4, 5, 5, 5, 9, 6], [5, 5, 9, 6, 5, 9, 12, 9, 6, 5], [9, 12, 11, 12, 9, 10, 10, 10, 8, 12]]


In [32]:
cv2.destroyAllWindows() 

In [12]:
print(result)

[[[173 177 182]
  [168 172 177]
  [162 166 171]
  ...
  [143 151 151]
  [142 150 150]
  [139 147 147]]

 [[170 174 179]
  [164 168 173]
  [156 160 165]
  ...
  [138 146 146]
  [138 146 146]
  [136 144 144]]

 [[168 172 177]
  [163 167 172]
  [150 154 159]
  ...
  [133 139 139]
  [130 137 137]
  [127 135 135]]

 ...

 [[173 179 182]
  [157 162 165]
  [133 138 141]
  ...
  [ 98 108 111]
  [125 137 139]
  [131 142 144]]

 [[174 179 182]
  [165 170 173]
  [155 160 163]
  ...
  [119 129 131]
  [131 141 143]
  [133 142 145]]

 [[174 178 181]
  [171 176 179]
  [169 174 177]
  ...
  [139 146 149]
  [140 147 150]
  [142 149 152]]]


In [ ]:
print()